.DELETE_ON_ERROR:

all: /net/frodo/home/khlin/p4/start.runmake.p4.OK callmainSim_1000.OK callmainSim_1001.OK callmainSim_1002.OK callmainSim_1003.OK callmainSim_1004.OK callmainSim_1005.OK callmainSim_1006.OK callmainSim_1007.OK callmainSim_1008.OK callmainSim_1009.OK callmainSim_1010.OK callmainSim_1011.OK callmainSim_1012.OK callmainSim_1013.OK callmainSim_1014.OK callmainSim_1015.OK callmainSim_1016.OK callmainSim_1017.OK callmainSim_1018.OK callmainSim_1019.OK pasteResults.OK delTempFile.OK backupResult.OK /net/frodo/home/khlin/p4/end.runmake.p4.OK

/net/frodo/home/khlin/p4/start.runmake.p4.OK : 
	[ ! -f /net/frodo/home/khlin/p4/runmake_p4_time.log ] && echo > /net/frodo/home/khlin/p4/runmake_p4_time.log; date | awk '{print "Simulations pipeline\n\nstart: "$$0}' >> /net/frodo/home/khlin/p4/runmake_p4_time.log
	touch /net/frodo/home/khlin/p4/start.runmake.p4.OK

callmainSim_1000.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1000 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff NA family_strct "2g.2f.2c" < mainSim.R > mainSim1000_100_0_1000_NA_0.01_"2g.2f.2c".Rout 2>&1 
	touch callmainSim_1000.OK

callmainSim_1001.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1001 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff NA family_strct "2g.2f.2c" < mainSim.R > mainSim1001_100_0_1000_NA_0.01_"2g.2f.2c".Rout 2>&1 
	touch callmainSim_1001.OK

callmainSim_1002.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1002 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff NA family_strct "2g.2f.2c" < mainSim.R > mainSim1002_100_0_1000_NA_0.01_"2g.2f.2c".Rout 2>&1 
	touch callmainSim_1002.OK

callmainSim_1003.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1003 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff NA family_strct "2g.2f.2c" < mainSim.R > mainSim1003_100_0_1000_NA_0.01_"2g.2f.2c".Rout 2>&1 
	touch callmainSim_1003.OK

callmainSim_1004.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1004 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff NA family_strct "2g.2f.2c" < mainSim.R > mainSim1004_100_0_1000_NA_0.01_"2g.2f.2c".Rout 2>&1 
	touch callmainSim_1004.OK

callmainSim_1005.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1005 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff NA family_strct "2g.2f.2c" < mainSim.R > mainSim1005_100_0_1000_NA_0.01_"2g.2f.2c".Rout 2>&1 
	touch callmainSim_1005.OK

callmainSim_1006.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1006 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff NA family_strct "2g.2f.2c" < mainSim.R > mainSim1006_100_0_1000_NA_0.01_"2g.2f.2c".Rout 2>&1 
	touch callmainSim_1006.OK

callmainSim_1007.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1007 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff NA family_strct "2g.2f.2c" < mainSim.R > mainSim1007_100_0_1000_NA_0.01_"2g.2f.2c".Rout 2>&1 
	touch callmainSim_1007.OK

callmainSim_1008.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1008 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff NA family_strct "2g.2f.2c" < mainSim.R > mainSim1008_100_0_1000_NA_0.01_"2g.2f.2c".Rout 2>&1 
	touch callmainSim_1008.OK

callmainSim_1009.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1009 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff NA family_strct "2g.2f.2c" < mainSim.R > mainSim1009_100_0_1000_NA_0.01_"2g.2f.2c".Rout 2>&1 
	touch callmainSim_1009.OK

callmainSim_1010.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1010 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff 1.645 family_strct "2g.2a.2u" < mainSim.R > mainSim1010_100_0_1000_1.645_0.01_"2g.2a.2u".Rout 2>&1 
	touch callmainSim_1010.OK

callmainSim_1011.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1011 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff 1.645 family_strct "2g.2a.2u" < mainSim.R > mainSim1011_100_0_1000_1.645_0.01_"2g.2a.2u".Rout 2>&1 
	touch callmainSim_1011.OK

callmainSim_1012.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1012 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff 1.645 family_strct "2g.2a.2u" < mainSim.R > mainSim1012_100_0_1000_1.645_0.01_"2g.2a.2u".Rout 2>&1 
	touch callmainSim_1012.OK

callmainSim_1013.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1013 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff 1.645 family_strct "2g.2a.2u" < mainSim.R > mainSim1013_100_0_1000_1.645_0.01_"2g.2a.2u".Rout 2>&1 
	touch callmainSim_1013.OK

callmainSim_1014.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1014 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff 1.645 family_strct "2g.2a.2u" < mainSim.R > mainSim1014_100_0_1000_1.645_0.01_"2g.2a.2u".Rout 2>&1 
	touch callmainSim_1014.OK

callmainSim_1015.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1015 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff 1.645 family_strct "2g.2a.2u" < mainSim.R > mainSim1015_100_0_1000_1.645_0.01_"2g.2a.2u".Rout 2>&1 
	touch callmainSim_1015.OK

callmainSim_1016.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1016 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff 1.645 family_strct "2g.2a.2u" < mainSim.R > mainSim1016_100_0_1000_1.645_0.01_"2g.2a.2u".Rout 2>&1 
	touch callmainSim_1016.OK

callmainSim_1017.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1017 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff 1.645 family_strct "2g.2a.2u" < mainSim.R > mainSim1017_100_0_1000_1.645_0.01_"2g.2a.2u".Rout 2>&1 
	touch callmainSim_1017.OK

callmainSim_1018.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1018 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff 1.645 family_strct "2g.2a.2u" < mainSim.R > mainSim1018_100_0_1000_1.645_0.01_"2g.2a.2u".Rout 2>&1 
	touch callmainSim_1018.OK

callmainSim_1019.OK : 
	srun -p nomosix,main -J p4 -D /net/frodo/home/khlin/p4 --time=1-0:0 --exclude=dl3601 R --vanilla --args seed 1019 n_rep 100 r 0 f 0.01 n_family 1000 trait_mean 0 dis_cutoff 1.645 family_strct "2g.2a.2u" < mainSim.R > mainSim1019_100_0_1000_1.645_0.01_"2g.2a.2u".Rout 2>&1 
	touch callmainSim_1019.OK

pasteResults.OK : callmainSim_1000.OK callmainSim_1001.OK callmainSim_1002.OK callmainSim_1003.OK callmainSim_1004.OK callmainSim_1005.OK callmainSim_1006.OK callmainSim_1007.OK callmainSim_1008.OK callmainSim_1009.OK callmainSim_1010.OK callmainSim_1011.OK callmainSim_1012.OK callmainSim_1013.OK callmainSim_1014.OK callmainSim_1015.OK callmainSim_1016.OK callmainSim_1017.OK callmainSim_1018.OK callmainSim_1019.OK
	Rscript paste_mainSim_results.R
	touch pasteResults.OK

delTempFile.OK : pasteResults.OK
	rm -f result*.txt mendelian*.txt gene*.txt weight*.txt variant_pass*.txt data*.ped
	touch delTempFile.OK

backupResult.OK : delTempFile.OK
	cp * p4/
	touch backupResult.OK

/net/frodo/home/khlin/p4/end.runmake.p4.OK : pasteResults.OK
	date | awk '{print "\n\nend: "$$0}' >> /net/frodo/home/khlin/p4/runmake_p4_time.log
	touch /net/frodo/home/khlin/p4/end.runmake.p4.OK

clean : 
	rm -f *.OK *.log *.csv *.Rout* *.out* result*.txt mendelian*.txt gene*.txt weight*.txt variant_pass*.txt data*.ped

clean_job : 
	ps xu | grep make | grep p4 | awk '{print $$2}' | xargs --verbose kill; scancel -n p4

